name: rps-cnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - jupyter
  - notebook
  - pip
  - pip:
      - ipykernel
